{{- if .Values.adminUser.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-ui.adminUserName" . }}
  labels:
    {{- include "k8s-ui.labels" . | nindent 4 }}
  {{- with .Values.adminUser.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: kubernetes-dashboard
{{- end }}
